env: "prod" 
api_key: "${API_KEY}"  
redis:
  host: "localhost"
  port: "6379"
  password: "${REDIS_PASSWORD}"
  db: 0

postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "${POSTGRES_PASSWORD}"
  database: "dictionary"  