env: "dev"
api_key: "sk_66b5ad520917f56228f2d49da8d3f27a9e8477ad66573dd6"  
redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0

postgres:
  host: "postgres"
  port: "5432"
  username: "postgres"
  password: "kolyaseroux"
  database: "dictionary"  